# DIBUAT OLEH: M ARKAN RAIHAN NUGRAHA
# TANGGAL DIBUAT: 06 NOVEMBER 2024
# PROGRAM PENGULANGAN BINTANG YANG BERTAMBAH SEBANYAK 5 KALI SECARA VERTIKAL

print('='*20)
print('PROGRAM LOOPING 11')
print('='*20)

for i in range(1, 6):
    print('*' * i)