# DIBUAT OLEH: M ARKAN RAIHAN NUGRAHA
# TANGGAL DIBUAT: 06 NOVEMBER 2024
# PROGRAM PENGULANGAN 12345 SEBANYAK 5 KALI SECARA VERTIKAL

print('='*20)
print('PROGRAM LOOPING 9')
print('='*20)

for i in range(5):
    print('1 2 3 4 5')