# DIBUAT OLEH: M ARKAN RAIHAN NUGRAHA
# TANGGAL DIBUAT: 06 NOVEMBER 2024
# PROGRAM PENGULANGAN BINTANG YANG BERKURANG SEBANYAK 5 KALI SECARA VERTIKAL

print('='*20)
print('PROGRAM LOOPING 12')
print('='*20)

for i in range(5, 0, -1):
    print('*' * i)