# DIBUAT OLEH: M ARKAN RAIHAN NUGRAHA
# TANGGAL DIBUAT: 07 NOVEMBER 2024
# PROGRAM PENGULANGAN BINTANG YANG BERTAMBAH DARI 1 SAMPAI 5 DAN MENYUSUN BERBENTUK SEGITIGA

print('='*20)
print('PROGRAM LOOPING 15')
print('='*20)

for i in range(5):
    print(' ' * (5 - i - 1) + '* ' * (i + 1))