# DIBUAT OLEH: M ARKAN RAIHAN NUGRAHA
# TANGGAL DIBUAT: 08 NOVEMBER 2024
# PROGRAM MENAMPILKAN NAMA DAN KELAS DITENGAH BINTANG

print('='*20)
print('PROGRAM SOAL 1')
print('='*20)

print('*'*42)
print('PROGRAM PYTHON'.center(42))
print('OLEH: M ARKAN RAIHAN NUGRAHA'.center(42))
print('KELAS: X PPLG 2'.center(42))
print('*'*42)