# DIBUAT OLEH: M ARKAN RAIHAN NUGRAHA
# TANGGAL DIBUAT: 08 NOVEMBER 2024
# PROGRAM MENAMPILKAN STRING, ANGKA BERKOMA, DAN ANGKA BULAT DALAM SETIAP BARIS BERBEDA

print('='*20)
print('PROGRAM SOAL 2')
print('='*20)

print('''
M Arkan RAIHAN NUGRAHA
58,5
168''')